import type { DiagnosticConfig } from '../types';

const config: DiagnosticConfig = {
  slug: 'ai-governance-maturity',
  scoreDisplay: 'normalized' as const,
  title: 'Execution-Layer AI Governance: Tactical Maturity',
  description: 'Assess your organization\'s AI governance maturity across six execution-layer pillars — from strategy and data security to build-time compliance, runtime enforcement, observability, and org topology — and receive a personalized GovOps roadmap.',
  dimensions: [
    {
      id: 'strategy',
      label: 'Strategy & Technical Blueprinting',
      shortName: 'Strategy',
      description: 'Creating an AI Governance Strategy linked to Business Strategy while leveraging automated, technology-enabled compliance solutions to mitigate liability, establish clear ownership, and drive enterprise trust.',
    },
    {
      id: 'data',
      label: 'Data & Vector-Space Security',
      shortName: 'Data Security',
      description: 'Securing unstructured and high-dimensional data assets, ensuring privacy and compliance at the data layer, and preventing vector space exploits such as data poisoning or unauthorized leaks.',
    },
    {
      id: 'build',
      label: 'Build-Time Pipelines & AIBOM Compliance',
      shortName: 'Build & AIBOM',
      description: 'Establishing secure, automated build pipelines that generate verifiable, machine-readable evidence (AIBOM) and enforce compliance-as-code policies prior to deployment.',
    },
    {
      id: 'runtime',
      label: 'Runtime Enforcement & Agentic Security',
      shortName: 'Runtime',
      description: 'Deploying decoupled real-time gateways, semantic firewalls, and kernel-level controls to intercept and enforce policy boundaries on live system prompts and autonomous agent actions.',
    },
    {
      id: 'telemetry',
      label: 'Telemetry, Observability & Continuous Evaluation',
      shortName: 'Telemetry',
      description: 'Designing continuous monitoring systems to track model drift, logging step-by-step reasoning for auditability, and generating automatic compliance evidence from real-time operations.',
    },
    {
      id: 'org',
      label: 'Org Topology, Change Networks & SRE Culture',
      shortName: 'Org & Culture',
      description: 'Establishing a cross-functional AI governance board, embedding specialized GovOps engineers in agile development, and utilizing change networks to turn operational telemetry into updated policies.',
    },
  ],
  questions: [
    // Pillar 1: Strategy & Technical Blueprinting
    { id: 'p1q1', dimension: 'strategy', text: 'How are your organization\'s AI use cases identified and inventoried?', options: ['No inventory exists; shadow AI deployments occur across departments.', 'Ad-hoc inventories are kept manually in isolated departmental spreadsheets.', 'A centralized, documented model registry tracks all production models.', 'Registry is managed as machine-readable configuration with clear risk-tiering.', 'Registry is dynamically integrated with GitOps pipelines and auto-discovered.'] },
    { id: 'p1q2', dimension: 'strategy', text: 'How are AI regulatory and legal risks evaluated during strategy formulation?', options: ['Risks are ignored; models are deployed with no legal or regulatory review.', 'Legal teams conduct manual, reactive reviews only after an incident occurs.', 'Standardized templates define and evaluate "High Risk" use cases before development.', 'Domain-specific compliance requirements (e.g., HIPAA, GDPR) are mapped to technical controls.', 'Automated OSCAL-based mapping models dynamically verify compliance posture across jurisdictions.'] },
    { id: 'p1q3', dimension: 'strategy', text: 'What is the relationship between business strategy and AI governance?', options: ['Governance is seen as a cost center and a barrier to business speed.', 'Basic guidelines exist but are routinely bypassed to maintain project delivery.', 'Governance goals are explicitly linked to business objectives and customer trust.', 'The strategic blueprint balances risk and velocity through structured review gates.', 'AI operates as a core strategic operating model with automated "governed enablement".'] },
    { id: 'p1q4', dimension: 'strategy', text: 'How is ownership and accountability assigned for AI assets?', options: ['Ownership is completely undefined; developers deploy models autonomously.', 'Individual project champions hold informal responsibility for specific pilots.', 'Centralized ownership is documented, and accountability is assigned per model.', 'Accountability is integrated into organizational roles, job descriptions, and vendor policies.', 'Real-time machine identities and workload attestations cryptographically bind ownership.'] },
    { id: 'p1q5', dimension: 'strategy', text: 'What is the maturity of your AI transformation roadmap?', options: ['No transformation roadmap exists; initiatives are entirely reactive.', 'Static project-level roadmaps exist but lack prioritization or dependency mapping.', 'A pragmatic roadmap sequences use cases based on business value and feasibility.', 'The roadmap is dynamic and updated periodically based on performance metrics.', 'Real-time operational feedback continuously optimizes and automates strategic prioritization.'] },

    // Pillar 2: Data & Vector-Space Security
    { id: 'p2q1', dimension: 'data', text: 'How is personally identifiable information (PII) managed in your AI data pipelines?', options: ['Data containing raw PII is fed directly into models and vector stores without sanitization.', 'Developers write manual, inconsistent custom scripts to scrub obvious PII before ingestion.', 'Standardized, automated pipelines utilize specialized tools to scrub PII during ingestion.', 'Real-time, context-aware PII masking occurs on both input queries and output payloads.', 'Differential privacy or advanced anonymization occurs automatically at the database level.'] },
    { id: 'p2q2', dimension: 'data', text: 'How are access controls enforced on your vector databases?', options: ['No access controls exist; vector databases are completely open and unencrypted.', 'Database is protected by static, shared credentials with no granular restrictions.', 'Role-Based Access Control (RBAC) restricts read/write/delete permissions by user group.', 'Granular pre-retrieval filters restrict similarity searches to authorized workspaces.', 'Real-time, zero-trust token-based controls dynamically authorize vector subspaces.'] },
    { id: 'p2q3', dimension: 'data', text: 'How is the security classification (ACL) of source documents handled in RAG systems?', options: ['ACLs are ignored; any vectorized document is visible to any user query.', 'Document-level tags exist in databases but are not strictly enforced during retrieval.', 'Vectors inherit parent document sensitivity labels to enable standard access checks.', 'Chunk-level ACL metadata inheritance is strictly enforced during pre-retrieval phases.', 'Source document ACL changes propagate and re-index vector spaces in real time.'] },
    { id: 'p2q4', dimension: 'data', text: 'What measures protect your vector space from poisoning or manipulation?', options: ['No security measures exist; the system accepts and indexes any incoming embedding.', 'Ingestion points are limited by IP address, but no mathematical validation occurs.', 'Ingested embeddings are checksummed and signed before being stored.', 'Anomaly detection monitors dimensional variance to block poisoned embeddings.', 'Self-healing data fabrics automatically isolate and roll back poisoned vector clusters.'] },
    { id: 'p2q5', dimension: 'data', text: 'How are data deletion requests (e.g., GDPR "right to be forgotten") handled?', options: ['Deletion requests are ignored or manually deleted from raw source databases only.', 'Manual scripts attempt to trace and delete corresponding vectors when requested.', 'Standardized APIs automate deletion of specific metadata and associated vectors.', 'Automated workflows purge deleted records across vector databases and model caching layers.', 'Graph-backed lineage engines continuously propagate deletion events, purging dependencies automatically.'] },

    // Pillar 3: Build-Time Pipelines & AIBOM Compliance
    { id: 'p3q1', dimension: 'build', text: 'How are model dependencies, datasets, and configurations tracked during development?', options: ['No tracking exists; models are deployed manually from local developer environments.', 'Standard software package dependencies are tracked, but ML-specific components are ignored.', 'Automated CI/CD pipelines track and document model versions and basic dependencies.', 'Build pipelines generate comprehensive, machine-readable AI Bills of Materials (AIBOMs).', 'Every build outputs cryptographically signed in-toto attestations alongside the AIBOM.'] },
    { id: 'p3q2', dimension: 'build', text: 'What standard schema is used to document your AI supply chain?', options: ['No schema is used; documentation is non-existent or unstructured text.', 'Custom, internal spreadsheets are manually updated with every model release.', 'Traditional SBOM formats are utilized, capturing only basic software packages.', 'Industry-standard CycloneDX 1.7 (ML profile) or SPDX 3.0.1 (AI profile) is enforced.', 'AIBOM schemas are enriched with cryptographically verified supply-chain metadata.'] },
    { id: 'p3q3', dimension: 'build', text: 'How are compliance and risk policies enforced during the build phase?', options: ['No build-time policy checks exist; compliance is evaluated post-deployment, if at all.', 'Developers run basic, manual code-review checklists before committing code.', 'Automated static application security testing (SAST) scans repositories for code vulnerabilities.', 'Policy-as-code engines (OPA, Conftest) evaluate AIBOM metadata, failing builds on policy violations.', 'Hard build gates prevent compilation of models exceeding defined bias, fairness, or accuracy thresholds.'] },
    { id: 'p3q4', dimension: 'build', text: 'How is the training environment\'s integrity validated?', options: ['Insecure environments; developers compile and train models on unsecured local machines.', 'Basic cloud environment parameters are logged, but no verification occurs.', 'Centralized training clusters log framework and dependency hashes.', 'Neutral, third-party observer platforms capture and verify training metadata.', 'Cryptographic hashes of the codebase\'s AST and compilation environment are sealed as evidence.'] },
    { id: 'p3q5', dimension: 'build', text: 'How are third-party or open-weights models validated?', options: ['Sourced models are downloaded and run directly with no validation.', 'Inbound packages are scanned for traditional software malware only.', 'Inbound model files (e.g., GGUF, SafeTensors) are registered in a central repository.', 'Vendor AIBOMs are programmatically validated against corporate compliance schemas.', 'Third-party models undergo continuous red-teaming and signature verification prior to execution.'] },

    // Pillar 4: Runtime Enforcement & Agentic Security
    { id: 'p4q1', dimension: 'runtime', text: 'How are safety and security boundaries enforced on model prompts and agent actions?', options: ['Boundaries rely entirely on natural-language system prompt engineering.', 'Brittle regex or keyword filters inspect model inputs and outputs within application code.', 'Decoupled API gateways (AgentCore Gateway, LiteLLM) enforce declarative policies.', 'Inline stateless Semantic Firewalls dynamically block adversarial drift and prompt injections.', 'Hardware-isolated enclaves and Grammar-Constrained Decoding guarantee deterministic execution.'] },
    { id: 'p4q2', dimension: 'runtime', text: 'How are the API keys, credentials, and secrets of your AI systems secured?', options: ['Secrets are hardcoded directly into configuration files, scripts, or system prompts.', 'Secrets are stored in standard environment variables, visible to the application runtime.', 'Credentials are centralized in standard vaults but are directly accessible by the model.', 'Gateway-mediated credentials ensure that sensitive API tokens are never exposed to the model.', 'Short-lived, workload-issued identities (SPIFFE/SPIRE) are dynamically rotated at runtime.'] },
    { id: 'p4q3', dimension: 'runtime', text: 'What permission model governs autonomous agentic workflows?', options: ['Agents execute actions with unrestricted root or admin permissions.', 'Permissions are bound to a single, broad corporate account with excessive privileges.', 'Standard RBAC defines distinct permission scopes for different agent groups.', 'Token-Based Access Control (TBAC) authorizes actions based on multi-credential presentation.', 'Least-privilege process boundaries are enforced at the OS level via eBPF LSM filters.'] },
    { id: 'p4q4', dimension: 'runtime', text: 'How are high-risk actions (e.g., financial transfers, file deletions) controlled?', options: ['Agents execute actions autonomously with no human oversight or restriction.', 'Human oversight is recommended but not technically enforced in the workflow.', 'Gateway-level policy blocks unauthorized write operations.', 'Human-in-the-loop validation is hardcoded into application gates for specific endpoints.', 'Enclave-verified policy engines enforce strict, cryptographically validated approval signatures.'] },
    { id: 'p4q5', dimension: 'runtime', text: 'How are multi-agent communication networks secured?', options: ['Inter-agent traffic occurs in the clear over unencrypted channels with no authentication.', 'Standard network firewalls restrict communication to internal subnets.', 'API proxies authenticate inter-agent connections using standard tokens.', 'Decentralized Identifiers (DIDs) establish cryptographic identities for each agent.', 'Inter-Agent Trust Protocol (IATP) manages secure handshakes within isolated meshes.'] },

    // Pillar 5: Telemetry, Observability & Continuous Evaluation
    { id: 'p5q1', dimension: 'telemetry', text: 'How is your production AI system\'s performance tracked and logged?', options: ['No systematic logging is implemented; failures are discovered by end-users.', 'Basic, generic server logs record HTTP status codes and token usage.', 'Specialized LLM tracing tools capture multi-step transactions, latencies, and costs.', 'Observability sinks run continuous evaluation models to score accuracy and bias.', 'Telemetry pipelines stream live, machine-readable compliance packages (OSCAL format).'] },
    { id: 'p5q2', dimension: 'telemetry', text: 'How does your system explain autonomous decisions to auditors or regulators?', options: ['Decisions are a complete "black box"; the system cannot explain outputs.', 'Standard text logs capture output payloads, but the reasoning path is lost.', 'High-level system prompts request the model to explain its logic in responses.', 'Truncated Chain-of-Thought (CoT) reasoning is preserved in immutable datastores.', 'Signed, forensic-grade execution evidence logs map inputs, logic, and policy decisions.'] },
    { id: 'p5q3', dimension: 'telemetry', text: 'How is model drift or performance degradation detected in production?', options: ['Drift is undetected until users report errors or inaccurate outputs.', 'Engineers periodically sample production outputs to manually evaluate performance.', 'Standard statistical monitoring tracks basic output length, token speed, and latency.', 'Automated tests run "Hallucination Variance" checks against golden datasets.', 'Real-time anomaly detection flags semantic intent deviations and behavioral drift instantly.'] },
    { id: 'p5q4', dimension: 'telemetry', text: 'What happens when an operational AI system encounters an undefined scenario?', options: ['The system hallucinates or fails catastrophically with no controlled exception handling.', 'Basic try-catch code wrapper blocks the raw system exception, returning a generic error.', 'Gateway intercepts the failure and logs the incident for manual developer review.', 'Automated fallback routines swap traffic to a simpler, deterministic rule-based model.', 'Self-healing environments partition the failed instance, deploying a known-safe model instantly.'] },
    { id: 'p5q5', dimension: 'telemetry', text: 'How frequently are compliance audits conducted on live systems?', options: ['Audits are never conducted, or occur only in response to a regulatory investigation.', 'Manual audits are conducted on an ad-hoc, retroactive basis using Excel sheets.', 'Audits are scheduled periodically (e.g., annually or quarterly) using standardized checklists.', 'Automated validation scans evaluate compliance posture weekly against target frameworks.', 'Continuous monitoring generates real-time, audit-ready compliance packages every day.'] },

    // Pillar 6: Org Topology, Change Networks & SRE Culture
    { id: 'p6q1', dimension: 'org', text: 'What is the structure of AI governance roles within your organization?', options: ['No dedicated AI governance roles; development is completely siloed.', 'Cross-functional, ad-hoc committees meet sporadically but have no veto authority.', 'A formal AI Governance Board is established with clear charter and escalation paths.', 'GovOps specialists are embedded directly within sprint teams to author automated gates.', 'Joint engineering-compliance teams manage continuous integration and real-time gateways.'] },
    { id: 'p6q2', dimension: 'org', text: 'How are developers trained on AI risk and responsible guardrails?', options: ['No training is provided; developers are unaware of AI-specific risk factors.', 'Voluntary, ad-hoc seminars discuss general ethical guidelines.', 'Mandatory onboarding modules train developers on standard security and privacy rules.', 'Targeted, hands-on workshops align developers on GitOps compliance-as-code tools.', 'Global Change Agent Networks continuously disseminate telemetry findings and upskill staff.'] },
    { id: 'p6q3', dimension: 'org', text: 'How is developer resistance to compliance measures managed?', options: ['Resistance is ignored; compliance is bypassed, creating high operational risk.', 'Strict, manual reviews are enforced, creating frustration and halting deployments.', 'Clear communication from leadership explains the strategic necessity of guardrails.', 'DevSecOps tooling automates checks, minimizing friction and developer workload.', 'Compliance is treated as an engineering asset ("governed enablement"), accelerating releases.'] },
    { id: 'p6q4', dimension: 'org', text: 'What is the operational feedback loop for AI incidents?', options: ['No formal incident response; problems are patched silently without documentation.', 'Post-incident reviews are manual and ad-hoc; lessons are not systematically applied.', 'Standardized playbooks define incident severity, ownership, and escalation paths.', 'Root Cause Analysis (RCA) feeds into manual updates of acceptable use policies.', 'Operational telemetry triggers automatic, real-time updates to declarative policy libraries.'] },
    { id: 'p6q5', dimension: 'org', text: 'How does your organization foster AI safety innovation?', options: ['AI safety is not a consideration; the sole focus is on system capability.', 'Basic security patches are applied reactively when vulnerabilities are exposed.', 'Dedicated resources are allocated to research and document emerging AI risk frameworks.', 'Teams actively experiment with advanced semantic firewalls and testing pipelines.', 'The organization collaborates in public repositories to shape next-generation safety standards.'] },
  ],
};

export default config;
