import type { DiagnosticConfig } from '../types';

const config: DiagnosticConfig = {
  slug: 'ai-governance-maturity',
  scoreDisplay: 'normalized' as const,
  title: 'Execution-Layer AI Governance: Tactical Maturity',
  description: 'Assess your organization\'s AI governance maturity across six execution-layer pillars — from strategy and data security to build-time compliance, runtime enforcement, observability, and org topology — and receive a personalized GovOps roadmap.',
  dimensions: [
    {
      id: 'strategy',
      label: 'Strategy & Technical Blueprinting',
      shortName: 'Strategy',
      description: 'Creating an AI Governance Strategy linked to Business Strategy while leveraging automated, technology-enabled compliance solutions to mitigate liability, establish clear ownership, and drive enterprise trust.',
    },
    {
      id: 'data',
      label: 'Data & Vector-Space Security',
      shortName: 'Data Security',
      description: 'Securing unstructured and high-dimensional data assets, ensuring privacy and compliance at the data layer, and preventing vector space exploits such as data poisoning or unauthorized leaks.',
    },
    {
      id: 'build',
      label: 'Build-Time Pipelines & AIBOM Compliance',
      shortName: 'Build & AIBOM',
      description: 'Establishing secure, automated build pipelines that generate verifiable, machine-readable evidence (AIBOM) and enforce compliance-as-code policies prior to deployment.',
    },
    {
      id: 'runtime',
      label: 'Runtime Enforcement & Agentic Security',
      shortName: 'Runtime',
      description: 'Deploying decoupled real-time gateways, semantic firewalls, and kernel-level controls to intercept and enforce policy boundaries on live system prompts and autonomous agent actions.',
    },
    {
      id: 'telemetry',
      label: 'Telemetry, Observability & Continuous Evaluation',
      shortName: 'Telemetry',
      description: 'Designing continuous monitoring systems to track model drift, logging step-by-step reasoning for auditability, and generating automatic compliance evidence from real-time operations.',
    },
    {
      id: 'org',
      label: 'Org Topology, Change Networks & GovOps Culture',
      shortName: 'Org & Culture',
      description: 'Establishing a cross-functional AI governance board, embedding specialized GovOps engineers in agile development, and utilizing change networks to turn operational telemetry into updated policies.',
    },
  ],
  questions: [
    // Pillar 1: Strategy & Technical Blueprinting
    { id: 'p1q1', dimension: 'strategy', text: 'How are your organization\'s AI use cases identified and inventoried?', options: ['No inventory exists; shadow AI deployments occur across departments.', 'Ad-hoc inventories are kept manually in isolated departmental spreadsheets.', 'A centralized, documented model registry tracks all production models.', 'Registry is managed as machine-readable configuration with clear risk-tiering (Minimal → High Risk).', 'Registry is dynamically integrated with GitOps pipelines and auto-discovered via automated scanning.'] },
    { id: 'p1q2', dimension: 'strategy', text: 'How are AI regulatory and legal risks evaluated during strategy formulation?', options: ['Risks are ignored; models are deployed with no legal or regulatory review.', 'Legal teams conduct manual, reactive reviews only after an incident occurs.', 'Standardized templates define and evaluate "high risk" use cases before development begins.', 'Domain-specific requirements (e.g., HIPAA, GDPR) are mapped to specific technical controls and monitored.', 'OSCAL-based automated mapping models continuously verify compliance posture across all active regulatory jurisdictions.'] },
    { id: 'p1q3', dimension: 'strategy', text: 'What is the relationship between business strategy and AI governance?', options: ['Governance is seen as a cost center and an obstacle to business speed.', 'Basic guidelines exist but are routinely bypassed to maintain project delivery velocity.', 'Governance goals are explicitly linked to business objectives and customer trust commitments.', 'The strategic blueprint balances risk and velocity through structured, pre-approved review gates.', 'AI operates as a core strategic operating model with automated "governed enablement" — compliance accelerates, not blocks, deployment.'] },
    { id: 'p1q4', dimension: 'strategy', text: 'How is ownership and accountability assigned for AI assets?', options: ['Ownership is completely undefined; developers deploy models autonomously.', 'Individual project champions hold informal responsibility for specific pilots.', 'Centralized ownership is documented and accountability is formally assigned per model.', 'Accountability is integrated into organizational roles, job descriptions, and vendor contracts.', 'Machine identities and workload attestations cryptographically bind ownership and chain of custody at runtime.'] },
    { id: 'p1q5', dimension: 'strategy', text: 'What is the maturity of your AI transformation roadmap?', options: ['No transformation roadmap exists; initiatives are entirely reactive and unsequenced.', 'Static project-level roadmaps exist but lack business value prioritization or dependency mapping.', 'A pragmatic roadmap sequences use cases based on business value, risk, and technical feasibility.', 'The roadmap is dynamic and updated periodically based on performance metrics and regulatory change.', 'Real-time operational feedback continuously optimizes and automates strategic prioritization across the portfolio.'] },

    // Pillar 2: Data & Vector-Space Security
    { id: 'p2q1', dimension: 'data', text: 'How is personally identifiable information (PII) managed in your AI data pipelines?', options: ['Raw PII is fed directly into models and vector stores without sanitization.', 'Developers write manual, inconsistent scripts to scrub obvious PII before ingestion.', 'Standardized, automated pipelines use specialized tools (e.g., Microsoft Presidio) to scrub PII during ingestion.', 'Real-time, context-aware PII masking applies to both input queries and output payloads.', 'Differential privacy or advanced anonymization occurs automatically at the database level, with continuous audit evidence.'] },
    { id: 'p2q2', dimension: 'data', text: 'How are access controls enforced on your vector databases?', options: ['No access controls exist; vector databases are completely open and unencrypted.', 'Database is protected by static, shared credentials with no granular per-user restrictions.', 'Role-Based Access Control (RBAC) restricts read/write/delete permissions at the user-group level.', 'Granular pre-retrieval filters restrict similarity searches to authorized workspaces before any calculation occurs.', 'Real-time, zero-trust token-based controls dynamically authorize access to specific vector subspaces per session.'] },
    { id: 'p2q3', dimension: 'data', text: 'How is data retention and time-to-live (TTL) policy enforced in AI data stores?', options: ['No retention policy exists; data accumulates indefinitely in all AI data stores.', 'Retention guidelines exist in policy documents but enforcement is manual and infrequent.', 'Automated TTL rules enforce deletion from vector databases and model caches at defined intervals.', 'TTL policies are risk-tiered by data classification and automatically logged for audit evidence.', 'Graph-backed lineage engines propagate retention events across all dependent stores, caches, and training artefacts in real time.'] },
    { id: 'p2q4', dimension: 'data', text: 'How is the security classification (ACL) of source documents handled in RAG systems?', options: ['ACLs are ignored; any vectorized document is visible to any user query.', 'Document-level tags exist in the database but are not strictly enforced during retrieval.', 'Vectors inherit parent document sensitivity labels to enable standard access checks at retrieval time.', 'Chunk-level ACL metadata inheritance is strictly enforced during pre-retrieval phases before similarity calculations.', 'Source document ACL changes propagate instantly, triggering automatic re-indexing of affected vector spaces in real time.'] },
    { id: 'p2q5', dimension: 'data', text: 'What measures protect your vector space from poisoning or manipulation?', options: ['No protection measures exist; the system accepts and indexes any incoming embedding.', 'Ingestion points are limited by IP address, but no mathematical validation of embeddings occurs.', 'Ingested embeddings are checksummed and signed before being stored in the vector database.', 'Anomaly detection monitors dimensional variance to identify and block poisoned embedding submissions.', 'Self-healing data fabrics automatically isolate suspicious vector clusters and trigger rollback without service interruption.'] },

    // Pillar 3: Build-Time Pipelines & AIBOM Compliance
    { id: 'p3q1', dimension: 'build', text: 'How are AI model assets, dependencies, and configurations documented and tracked?', options: ['No tracking exists; models enter production with no documentation of provenance or dependencies.', 'SaaS: vendor models are logged informally in spreadsheets with no version or licensing verification. Build: models are deployed manually from local environments with no CI/CD tracking.', 'SaaS: a vendor registry records product names, versions, data-handling terms, and renewal dates. Build: automated CI/CD pipelines track model versions and basic software dependencies.', 'SaaS: vendor-supplied AIBOMs are collected during procurement and stored in a centralised inventory. Build: build pipelines generate machine-readable AIBOMs (CycloneDX 1.7 ML or SPDX 3.0.1 AI profile) on every run.', 'SaaS: vendor AIBOMs are programmatically validated against corporate compliance schemas at onboarding and on each update. Build: every build outputs cryptographically signed in-toto attestations alongside the AIBOM.'] },
    { id: 'p3q2', dimension: 'build', text: 'How are compliance and risk policies enforced before a model goes to production?', options: ['No pre-production policy checks exist; compliance is evaluated reactively post-deployment, if at all.', 'Developers or procurement teams run manual checklists before approving a model or vendor.', 'Automated scanning or static application security testing (SAST) checks repositories or vendor packages for known vulnerabilities.', 'SaaS: a vendor risk scoring engine evaluates AIBOM metadata against corporate policy, flagging non-compliant contracts. Build: policy-as-code engines (OPA/Conftest) evaluate AIBOM metadata and fail non-compliant builds automatically.', 'Hard policy gates prevent deployment of any model — sourced or built — that exceeds defined bias, fairness, licensing, or accuracy thresholds as defined in OSCAL.'] },
    { id: 'p3q3', dimension: 'build', text: 'How is the integrity and provenance of third-party or open-weights models validated?', options: ['Sourced models are downloaded and run directly with no integrity validation.', 'Inbound packages are scanned for traditional software malware only; ML-specific weights are not validated.', 'Model files (e.g., GGUF, SafeTensors) are registered in a central repository with recorded source and hash.', 'SaaS: vendor AIBOMs are programmatically validated against corporate compliance schemas before contract approval. Build: cryptographic signatures and licensing metadata of open-weights models are verified before use.', 'Third-party models undergo continuous automated red-teaming, signature verification, and adversarial stress testing before and after initial deployment.'] },
    { id: 'p3q4', dimension: 'build', text: 'How is the training environment\'s integrity validated? (Build-first organizations: answer directly. SaaS-first organizations: select L3 to reflect managed external delegation.)', options: ['SaaS-first: score as L3 — see question note. | Build: models are compiled and trained on unsecured local developer machines.', 'Build: basic cloud environment parameters are logged, but no formal verification of the training environment occurs.', 'Build: centralized training clusters log framework versions, dependency hashes, and hardware configurations. (SaaS-first: select this level.)', 'Build: neutral, third-party observer platforms capture and verify training metadata before model promotion.', 'Build: cryptographic hashes of the codebase AST and compilation environment are sealed as tamperproof evidence in the AIBOM.'] },
    { id: 'p3q5', dimension: 'build', text: 'How does your organization manage egress PII redaction for outbound AI payloads?', options: ['No egress controls exist; model outputs leave the organization\'s perimeter without inspection.', 'Manual review processes attempt to check sensitive outputs before external sharing, applied inconsistently.', 'Gateway-level rules scrub obvious PII categories (names, email addresses, credential patterns) from all outbound payloads.', 'Context-aware semantic redaction detects and strips implicit PII (indirect identifiers, combined attributes) in real time at the perimeter.', 'Cryptographic audit trails log every redaction event, providing tamperproof evidence of data minimisation compliance for each outbound payload.'] },

    // Pillar 4: Runtime Enforcement & Agentic Security
    { id: 'p4q1', dimension: 'runtime', text: 'How are safety and security boundaries enforced on model prompts and agent actions?', options: ['Boundaries rely entirely on natural-language system prompt engineering — no external technical controls.', 'Brittle regex or keyword filters inspect model inputs and outputs within application wrapper code.', 'Decoupled API gateways (e.g., AgentCore Gateway, LiteLLM) enforce declarative Cedar policies independently of LLM reasoning.', 'Inline stateless Semantic Firewalls calculate semantic tension and flow direction to dynamically block adversarial drift and prompt injections at the edge.', 'Hardware-isolated Trusted Execution Enclaves (TEEs) and Grammar-Constrained Decoding (GCD) guarantee deterministic, policy-bound execution.'] },
    { id: 'p4q2', dimension: 'runtime', text: 'How are API credentials and secrets secured across your AI systems?', options: ['Secrets are hardcoded directly into configuration files, scripts, or system prompts.', 'Secrets are stored in standard environment variables, directly accessible to the application runtime and model context.', 'Credentials are centralised in a secrets vault; the model receives short-lived, scoped tokens — never raw credentials — via gateway mediation.', 'Gateway-mediated credential injection ensures that sensitive API tokens are never exposed to or visible within the model\'s context window.', 'Short-lived SPIFFE/SPIRE workload identities are dynamically issued and rotated at runtime, eliminating long-lived credentials entirely.'] },
    { id: 'p4q3', dimension: 'runtime', text: 'What permission model governs autonomous agentic workflows?', options: ['Agents execute actions with unrestricted root or admin permissions across all connected systems.', 'Permissions are bound to a single, broad corporate account with excessive implicit privileges.', 'Standard RBAC defines distinct, scoped permission sets for different agent groups and task types.', 'Token-Based Access Control (TBAC) authorises actions based on multi-credential presentation and contextual session state.', 'Least-privilege process boundaries are enforced at the OS kernel level via eBPF LSM filters, independent of application logic.'] },
    { id: 'p4q4', dimension: 'runtime', text: 'How are high-risk actions (e.g., financial transfers, record deletions, external communications) controlled?', options: ['Agents execute all actions autonomously with no human oversight, approval gates, or restriction.', 'Human oversight is recommended in documentation but not technically enforced in the workflow execution path.', 'Gateway-level declarative policy blocks defined categories of unauthorised write operations before execution.', 'Human-in-the-loop validation is technically enforced at application gates for all pre-defined high-risk action endpoints.', 'Enclave-verified policy engines require cryptographically validated approval signatures before any irreversible action is executed.'] },
    { id: 'p4q5', dimension: 'runtime', text: 'How are multi-agent communication networks authenticated and secured?', options: ['Inter-agent traffic occurs in cleartext over unencrypted channels with no authentication.', 'Standard network firewalls restrict agent communication to internal subnets but no per-agent identity is established.', 'API proxies authenticate inter-agent connections using standard bearer tokens with defined scopes.', 'Decentralised Identifiers (DIDs) establish unique, verifiable cryptographic identities for each individual agent.', 'Cryptographic inter-agent trust protocols manage secure handshakes within isolated meshes, with continuous identity attestation throughout session lifetime.'] },

    // Pillar 5: Telemetry, Observability & Continuous Evaluation
    { id: 'p5q1', dimension: 'telemetry', text: 'How is your production AI system\'s performance tracked and logged?', options: ['No specialized logging is implemented; failures and hallucinations are discovered informally by end users.', 'Basic generic server logs record HTTP status codes and token usage but no reasoning-path data.', 'Specialized LLM tracing tools (e.g., Langfuse, Phoenix) capture multi-step transactions, tool calls, latencies, and costs.', 'Observability sinks run continuous evaluation models (LLM-as-a-judge) to score accuracy, bias, and fairness in real time.', 'Telemetry pipelines stream live, machine-readable compliance packages in OSCAL Assessment Results format, permanently audit-ready.'] },
    { id: 'p5q2', dimension: 'telemetry', text: 'How does your system explain autonomous decisions to auditors or regulators?', options: ['Decisions are a complete black box; the system cannot explain its outputs or reasoning.', 'Standard text logs capture output payloads, but the step-by-step reasoning path is lost after generation.', 'High-level system prompts request the model to include a rationale in its responses, but this is not stored separately.', 'Truncated Chain-of-Thought (CoT) reasoning is automatically preserved in immutable, encrypted log stores for every decision.', 'Signed, forensic-grade execution evidence logs map all inputs, intermediate logic steps, and policy decisions into a tamperproof audit record.'] },
    { id: 'p5q3', dimension: 'telemetry', text: 'How is model drift or performance degradation detected in production?', options: ['Drift is undetected until users report errors or demonstrably inaccurate outputs.', 'Engineers periodically sample production outputs to manually evaluate performance against expectations.', 'Standard statistical monitoring tracks output length, token speed, error rate, and latency over time.', 'Automated tests run "hallucination variance" checks against golden datasets and alert on statistical deviations.', 'Real-time anomaly detection flags semantic intent deviations and behavioural drift instantly, triggering automated triage workflows.'] },
    { id: 'p5q4', dimension: 'telemetry', text: 'What happens when a production AI system encounters an undefined or out-of-scope scenario?', options: ['The system hallucinates or fails catastrophically with no controlled exception handling or user notification.', 'Basic try-catch wrappers block the raw system exception, returning a generic error message to the user.', 'A gateway intercepts the failure, logs the incident, and routes to a manual developer review queue.', 'Automated fallback routines swap traffic to a simpler, deterministic rule-based model without service interruption.', 'Self-healing environments partition the failed model instance and deploy a known-safe verified fallback within seconds.'] },
    { id: 'p5q5', dimension: 'telemetry', text: 'How is compliance evidence generated and maintained for live AI systems?', options: ['No compliance evidence is generated from live systems; documentation is created manually if a regulatory investigation demands it.', 'Manual retrospective audits are conducted ad-hoc using spreadsheet exports and system logs.', 'Scheduled audits produce structured reports using standardised checklists; evidence is retained in a defined repository.', 'Automated validation scans continuously evaluate compliance posture and generate machine-readable evidence packages on a defined schedule.', 'Real-time telemetry generates OSCAL-formatted compliance evidence continuously — the organisation is permanently audit-ready without manual intervention.'] },

    // Pillar 6: Org Topology, Change Networks & GovOps Culture
    { id: 'p6q1', dimension: 'org', text: 'What is the structure and authority of AI governance roles within your organization?', options: ['No dedicated AI governance roles exist; all AI development is siloed within individual engineering teams.', 'Cross-functional, ad-hoc committees meet sporadically but hold no formal decision rights, veto authority, or budget.', 'A formal AI Governance Board is established with a clear charter, defined membership, and documented escalation paths.', 'GovOps specialists are embedded directly within sprint teams and write automated compliance gates alongside functional features.', 'Joint engineering-compliance teams co-own continuous integration pipelines and manage real-time runtime gateways as a shared operational responsibility.'] },
    { id: 'p6q2', dimension: 'org', text: 'How quickly does your organization detect, contain, and learn from an AI governance incident?', options: ['No formal incident response exists; AI failures are patched silently without documentation or post-mortem.', 'Incidents are addressed reactively; post-mortems are informal, inconsistent, and not systematically retained.', 'Standardised incident playbooks define severity tiers, ownership, containment steps, and escalation paths for AI-specific failures.', 'Root cause analyses (RCAs) from AI incidents are systematically fed back into compliance policy updates within a defined SLA.', 'Operational telemetry triggers automatic, real-time updates to declarative policy libraries — the feedback loop requires no manual intervention.'] },
    { id: 'p6q3', dimension: 'org', text: 'How is developer resistance to compliance measures managed?', options: ['Resistance is ignored; governance is routinely bypassed, creating untracked operational and regulatory risk.', 'Strict manual reviews are enforced top-down, creating developer friction, deployment bottlenecks, and adversarial culture.', 'Clear communication from leadership explains the strategic necessity of guardrails and links them to business outcomes.', 'DevSecOps tooling automates compliance checks, minimizing developer workload and shifting governance left into the IDE.', 'Compliance is treated as an engineering asset ("governed enablement") — pre-approved guardrails are faster than building from scratch, creating positive developer adoption.'] },
    { id: 'p6q4', dimension: 'org', text: 'How tightly is live operational telemetry connected to policy updates?', options: ['No connection exists; policies are static documents that are rarely, if ever, updated based on system behavior.', 'Policy updates are triggered manually when engineers or compliance officers notice a pattern in system logs.', 'Scheduled review cycles (quarterly or more frequent) incorporate operational data into policy revisions.', 'A formal Change Agent Network reviews live telemetry on a continuous basis and proposes policy-as-code updates through a peer-review process.', 'Findings from continuous telemetry monitoring are automatically compiled into declarative policy updates and pushed to production gateways via a GitOps loop.'] },
    { id: 'p6q5', dimension: 'org', text: 'How does your organization build and sustain internal AI governance capability over time?', options: ['No training, upskilling, or knowledge-sharing exists; AI governance expertise is entirely absent or held by one individual.', 'Voluntary, ad-hoc seminars discuss general ethical guidelines; attendance and impact are unmeasured.', 'Mandatory onboarding modules train all developers on AI-specific security, privacy, and acceptable-use rules.', 'Targeted hands-on workshops align developers on GitOps compliance-as-code tools, with proficiency tracked per team.', 'A global Change Agent Network continuously disseminates telemetry findings, drives upskilling, and embeds GovOps competency as a core organisational capability.'] },
  ],
};

export default config;
