import type { DiagnosticConfig } from '../types';

const config: DiagnosticConfig = {
  slug: 'ai-maturity',
  title: 'AI Navigator Checkup',
  description: 'Assess your organization\'s AI maturity across five key dimensions and receive a personalized roadmap.',
  dimensions: [
    { id: 'strategy', label: 'AI Strategy & Vision' },
    { id: 'data', label: 'Data Readiness' },
    { id: 'talent', label: 'Talent & Culture' },
    { id: 'technology', label: 'Technology & Infrastructure' },
    { id: 'governance', label: 'Governance & Ethics' },
  ],
  questions: [
    // AI Strategy & Vision
    {
      id: 'strategy_1',
      dimension: 'strategy',
      text: 'Our organization has a clearly defined AI strategy aligned with business objectives.',
      scale: 5,
      anchorLow: 'No strategy exists',
      anchorHigh: 'Fully defined and communicated',
    },
    {
      id: 'strategy_2',
      dimension: 'strategy',
      text: 'Senior leadership actively sponsors and champions AI initiatives.',
      scale: 5,
      anchorLow: 'No executive sponsorship',
      anchorHigh: 'Strong, consistent sponsorship',
    },
    {
      id: 'strategy_3',
      dimension: 'strategy',
      text: 'We have identified and prioritized specific use cases where AI can deliver business value.',
      scale: 5,
      anchorLow: 'No use cases identified',
      anchorHigh: 'Comprehensive prioritized roadmap',
    },
    {
      id: 'strategy_4',
      dimension: 'strategy',
      text: 'Our AI investments are linked to measurable business outcomes and ROI.',
      scale: 5,
      anchorLow: 'No linkage to outcomes',
      anchorHigh: 'Fully measured and tracked',
    },
    // Data Readiness
    {
      id: 'data_1',
      dimension: 'data',
      text: 'Our organization has high-quality, accessible data available for AI model training and inference.',
      scale: 5,
      anchorLow: 'Data is siloed and inconsistent',
      anchorHigh: 'Unified, clean, and accessible',
    },
    {
      id: 'data_2',
      dimension: 'data',
      text: 'We have established data governance policies (ownership, quality standards, lineage).',
      scale: 5,
      anchorLow: 'No governance in place',
      anchorHigh: 'Mature governance framework',
    },
    {
      id: 'data_3',
      dimension: 'data',
      text: 'Our data pipelines reliably deliver the volume and variety needed for AI workloads.',
      scale: 5,
      anchorLow: 'No pipelines exist',
      anchorHigh: 'Automated, scalable pipelines',
    },
    {
      id: 'data_4',
      dimension: 'data',
      text: 'We actively manage data privacy and compliance requirements for AI use.',
      scale: 5,
      anchorLow: 'Not addressed',
      anchorHigh: 'Fully compliant and audited',
    },
    // Talent & Culture
    {
      id: 'talent_1',
      dimension: 'talent',
      text: 'We have sufficient in-house AI/ML expertise (data scientists, ML engineers, AI product managers).',
      scale: 5,
      anchorLow: 'No internal expertise',
      anchorHigh: 'Strong, diverse AI team',
    },
    {
      id: 'talent_2',
      dimension: 'talent',
      text: 'Our broader workforce has the AI literacy needed to work alongside AI tools effectively.',
      scale: 5,
      anchorLow: 'Very low awareness',
      anchorHigh: 'Organization-wide AI fluency',
    },
    {
      id: 'talent_3',
      dimension: 'talent',
      text: 'Our organizational culture encourages experimentation and tolerates the failure rate inherent in AI projects.',
      scale: 5,
      anchorLow: 'Risk-averse, no experimentation',
      anchorHigh: 'Experimentation is the norm',
    },
    {
      id: 'talent_4',
      dimension: 'talent',
      text: 'We have a clear strategy for attracting, developing, and retaining AI talent.',
      scale: 5,
      anchorLow: 'No talent strategy',
      anchorHigh: 'Proactive, differentiated strategy',
    },
    // Technology & Infrastructure
    {
      id: 'technology_1',
      dimension: 'technology',
      text: 'Our technology infrastructure can support the compute and storage demands of AI workloads at scale.',
      scale: 5,
      anchorLow: 'Cannot support AI workloads',
      anchorHigh: 'Fully scalable and cloud-enabled',
    },
    {
      id: 'technology_2',
      dimension: 'technology',
      text: 'We have standardized tools and platforms for developing, deploying, and monitoring AI models (MLOps).',
      scale: 5,
      anchorLow: 'Ad hoc, no standards',
      anchorHigh: 'Mature MLOps platform',
    },
    {
      id: 'technology_3',
      dimension: 'technology',
      text: 'Our AI systems integrate smoothly with existing enterprise applications and workflows.',
      scale: 5,
      anchorLow: 'No integration',
      anchorHigh: 'Seamlessly integrated',
    },
    {
      id: 'technology_4',
      dimension: 'technology',
      text: 'We actively monitor and maintain AI models in production (drift detection, retraining).',
      scale: 5,
      anchorLow: 'No monitoring in place',
      anchorHigh: 'Automated monitoring and retraining',
    },
    // Governance & Ethics
    {
      id: 'governance_1',
      dimension: 'governance',
      text: 'We have policies and processes to ensure our AI systems are fair, unbiased, and transparent.',
      scale: 5,
      anchorLow: 'No policies exist',
      anchorHigh: 'Comprehensive and enforced policies',
    },
    {
      id: 'governance_2',
      dimension: 'governance',
      text: 'There is clear accountability for AI decisions and outcomes within our organization.',
      scale: 5,
      anchorLow: 'Accountability is unclear',
      anchorHigh: 'Clear ownership at every level',
    },
    {
      id: 'governance_3',
      dimension: 'governance',
      text: 'We assess and manage risks associated with AI deployments (security, reliability, regulatory).',
      scale: 5,
      anchorLow: 'Risks not assessed',
      anchorHigh: 'Formal risk management process',
    },
    {
      id: 'governance_4',
      dimension: 'governance',
      text: 'Our AI practices comply with relevant regulations and industry standards.',
      scale: 5,
      anchorLow: 'Compliance not addressed',
      anchorHigh: 'Fully compliant and audit-ready',
    },
  ],
};

export default config;
