import type { DiagnosticConfig } from '../types';

const safeAgileMaturit: DiagnosticConfig = {
  slug: 'safe-agile-maturity',
  title: 'SAFe Agile Maturity Assessment',
  description:
    'Assess your organization\'s SAFe Agile maturity across five pillars — Value Stream & Organizational Design, Strategic Funding & Portfolio Governance, Flow, Execution & Cadence, Technical Engineering & Architecture, and Leadership, Culture & Talent Capability — and receive a prioritized improvement roadmap.',
  scoreDisplay: 'normalized',
  dimensions: [
    { id: 'value-stream-org',      label: 'Value Stream & Organizational Design',     shortName: 'Value Stream & Org' },
    { id: 'strategic-funding',     label: 'Strategic Funding & Portfolio Governance',  shortName: 'Strategic Funding' },
    { id: 'flow-execution',        label: 'Flow, Execution & Cadence',                 shortName: 'Flow & Execution' },
    { id: 'technical-engineering', label: 'Technical Engineering & Architecture',      shortName: 'Technical Eng.' },
    { id: 'leadership-culture',    label: 'Leadership, Culture & Talent Capability',   shortName: 'Leadership & Culture' },
  ],
  questions: [
    // ── PILLAR 1: Value Stream & Organizational Design ───────────────────────
    {
      id: 'p1q1',
      dimension: 'value-stream-org',
      text: 'How many teams or functions does a typical feature pass through before reaching production?',
      options: [
        'Five or more teams/functions, with manual handoffs at each step',
        'Three to four teams/functions, coordinated informally',
        'Two to three teams, with some coordination structure in place',
        'Typically one to two teams; dependencies are rare',
        'Nearly always a single team owns the feature end-to-end',
      ],
    },
    {
      id: 'p1q2',
      dimension: 'value-stream-org',
      text: 'Are your Agile Release Trains organized around end-to-end value streams, or do they mirror the existing functional/system org chart?',
      options: [
        'ARTs directly mirror the legacy functional or component org chart',
        'Value streams are mapped on paper, but ART boundaries still follow old org lines',
        'At least one ART has been reorganized around a genuine value stream',
        'Most ARTs are organized around value streams with documented interfaces',
        'All ARTs are organized around value streams and design is continuously validated against flow',
      ],
    },
    {
      id: 'p1q3',
      dimension: 'value-stream-org',
      text: 'What percentage of features delivered last quarter required active coordination across more than one team or ART?',
      options: [
        '75–100% of features required cross-team coordination',
        '50–75%',
        '30–50%',
        '15–30%',
        'Less than 15%',
      ],
    },
    {
      id: 'p1q4',
      dimension: 'value-stream-org',
      text: 'Have you formally mapped your value streams (a value stream mapping exercise) within the past 12 months?',
      options: [
        'No value stream mapping has ever been performed',
        'A mapping exercise was attempted but not completed or adopted',
        'Value streams were mapped once, but not revisited since',
        'Value streams are mapped and referenced regularly in planning',
        'Value stream maps are living artifacts, reviewed and updated each PI',
      ],
    },
    {
      id: 'p1q5',
      dimension: 'value-stream-org',
      text: 'Are team interfaces explicitly documented — who owns what, and how platform, enabling, stream-aligned, and complicated-subsystem teams interact?',
      options: [
        'No defined team-interface model; team types and interactions are undefined',
        'Team types are informally understood but not documented',
        'Team interfaces are documented for at least one ART',
        'Team interfaces are documented across most ARTs and actively referenced',
        'Team interfaces are documented, monitored, and adjusted as flow patterns change',
      ],
    },
    {
      id: 'p1q6',
      dimension: 'value-stream-org',
      text: 'When delivery friction is identified, does the organization consider restructuring teams or ARTs, or does it only apply process fixes?',
      options: [
        'Only process/ceremony fixes are considered; restructuring is never discussed',
        'Restructuring is discussed informally but rarely acted on',
        'Restructuring has been used to solve friction on at least one occasion',
        'Restructuring is a standard tool considered alongside process fixes',
        'Org design is proactively adjusted before friction becomes a persistent problem',
      ],
    },
    {
      id: 'p1q7',
      dimension: 'value-stream-org',
      text: 'How frequently is team/ART design reviewed and adjusted based on where value-flow friction is actually occurring?',
      options: [
        "Never — org design was set once and hasn't been revisited",
        'Reviewed only during major reorganizations (multi-year cycles)',
        'Reviewed roughly once a year',
        'Reviewed each quarter or PI, using some data',
        'Reviewed continuously each PI using flow and dependency data',
      ],
    },
    {
      id: 'p1q8',
      dimension: 'value-stream-org',
      text: 'Can you name the specific value stream each ART is aligned to, and the end customer outcome it serves?',
      options: [
        'No — ARTs have no defined value stream or customer outcome mapping',
        'Some ARTs can name a general business area but not a specific outcome',
        'Most ARTs can name their value stream; outcome mapping is inconsistent',
        'All ARTs can name their value stream and the outcome it serves',
        "All ARTs can precisely articulate their value stream, outcome, and how it's measured",
      ],
    },

    // ── PILLAR 2: Strategic Funding & Portfolio Governance ───────────────────
    {
      id: 'p2q1',
      dimension: 'strategic-funding',
      text: 'What percentage of engineering/software investment is funded through continuous Value Stream funding versus annual fixed-scope projects?',
      options: [
        '0% — entirely annual, fixed-scope project funding',
        'Up to 25% continuous funding, the rest project-based',
        '25–50% continuous funding',
        '50–80% continuous funding',
        '80–100% continuous funding',
      ],
    },
    {
      id: 'p2q2',
      dimension: 'strategic-funding',
      text: 'Are Strategic Themes defined, documented, and actively used to prioritize portfolio investment?',
      options: [
        'No Strategic Themes are defined',
        'Strategic Themes exist as a document but are rarely referenced in decisions',
        'Strategic Themes are actively referenced in some portfolio decisions',
        'Strategic Themes consistently drive portfolio prioritization',
        'Strategic Themes are the explicit basis for every major investment decision',
      ],
    },
    {
      id: 'p2q3',
      dimension: 'strategic-funding',
      text: 'Is a Portfolio Kanban in place and actively used to manage the flow of Portfolio Epics?',
      options: [
        'No Portfolio Kanban exists',
        'A Portfolio Kanban exists but is not actively maintained',
        'Portfolio Kanban is maintained for some epics',
        'Portfolio Kanban is actively used to manage flow of most epics',
        'Portfolio Kanban is the authoritative, continuously maintained system of record',
      ],
    },
    {
      id: 'p2q4',
      dimension: 'strategic-funding',
      text: 'Are OKRs defined at the portfolio level, and reviewed on a regular cadence (quarterly or better)?',
      options: [
        'No OKRs are defined at the portfolio level',
        'OKRs are defined but reviewed less than annually, or not at all',
        'OKRs are defined and reviewed roughly annually',
        'OKRs are defined and reviewed quarterly',
        'OKRs are reviewed quarterly or more often and directly tied to funding decisions',
      ],
    },
    {
      id: 'p2q5',
      dimension: 'strategic-funding',
      text: 'Is Weighted Shortest Job First (WSJF), or an equivalent economic prioritization method, applied consistently across the portfolio?',
      options: [
        'No formal economic prioritization method is used',
        'WSJF is used occasionally and inconsistently applied',
        'WSJF is used for major initiatives only',
        'WSJF is applied consistently across most of the portfolio',
        'WSJF (or equivalent) is the default prioritization method portfolio-wide',
      ],
    },
    {
      id: 'p2q6',
      dimension: 'strategic-funding',
      text: 'How often is capital reallocated across value streams based on performance data, and what actually triggers that reallocation?',
      options: [
        'Capital is never reallocated outside the annual budget cycle',
        'Reallocation happens only in exceptional or crisis circumstances',
        'Reallocation happens annually, alongside planning',
        'Reallocation happens quarterly, tied to portfolio syncs',
        'Reallocation happens monthly or continuously, driven by live performance data',
      ],
    },
    {
      id: 'p2q7',
      dimension: 'strategic-funding',
      text: 'When priorities shift, how long does it typically take to redirect funding to the new priority?',
      options: [
        'Months — bound by the next annual budget cycle',
        'One to two quarters',
        'Within a single quarter',
        'Within a few weeks',
        'Near-immediately, within days',
      ],
    },
    {
      id: 'p2q8',
      dimension: 'strategic-funding',
      text: 'Does the finance/budgeting function participate directly in ART or portfolio planning events?',
      options: [
        'Finance has no involvement in ART/portfolio planning events',
        "Finance receives summaries after planning, but isn't directly involved",
        "Finance attends occasionally but doesn't actively shape decisions",
        'Finance regularly participates and informs prioritization',
        'Finance is an embedded, active partner in every planning and portfolio sync event',
      ],
    },

    // ── PILLAR 3: Flow, Execution & Cadence ─────────────────────────────────
    {
      id: 'p3q1',
      dimension: 'flow-execution',
      text: 'Are Flow Metrics — Velocity, Time, Load, Efficiency, Distribution, Predictability — actively tracked for your ARTs?',
      options: [
        'No Flow Metrics are tracked at all',
        'Some metrics are collected but not reviewed regularly',
        'Flow Metrics are tracked and reviewed for at least one ART',
        'Flow Metrics are tracked and reviewed across most ARTs',
        'Flow Metrics are tracked, reviewed, and actively drive decisions across all ARTs',
      ],
    },
    {
      id: 'p3q2',
      dimension: 'flow-execution',
      text: 'What is your current PI Predictability measure (committed versus delivered PI objectives)?',
      options: [
        'Not measured, or below 50%',
        '50–65%',
        '65–75%',
        '75–90%',
        'Above 90%',
      ],
    },
    {
      id: 'p3q3',
      dimension: 'flow-execution',
      text: 'Are WIP limits defined and actively enforced at both team and program levels?',
      options: [
        'No WIP limits are defined anywhere',
        'WIP limits are defined but not enforced',
        'WIP limits are enforced on at least one team/ART',
        'WIP limits are enforced across most teams and programs',
        'WIP limits are enforced consistently and adjusted based on flow data',
      ],
    },
    {
      id: 'p3q4',
      dimension: 'flow-execution',
      text: 'Do Inspect & Adapt workshops consistently produce specific, actionable backlog items that get worked in subsequent iterations?',
      options: [
        'I&A workshops rarely happen, or produce no backlog action',
        'I&A happens, but action items are rarely followed up on',
        'I&A produces action items about half the time',
        'I&A consistently (over half the time) produces items worked next PI',
        'I&A reliably produces prioritized, tracked action items every cycle',
      ],
    },
    {
      id: 'p3q5',
      dimension: 'flow-execution',
      text: 'Do System Demos show integrated, working software, or do they lean on status updates and slides?',
      options: [
        'System Demos are status-update slides, not working software',
        'Demos occasionally show working software, mostly status updates',
        'Demos usually show working software for some teams',
        'Demos consistently show integrated, working software',
        'Demos always show integrated, production-ready increments with stakeholder feedback captured',
      ],
    },
    {
      id: 'p3q6',
      dimension: 'flow-execution',
      text: 'Are cross-ART or cross-team dependencies identified and resolved before PI execution begins, or are they typically discovered mid-PI?',
      options: [
        'Dependencies are typically discovered mid-PI, causing rework',
        'Some dependency identification happens, but resolution is inconsistent',
        'Dependencies are identified before PI Planning for some ARTs',
        'Dependencies are resolved pre-PI for the large majority of cases',
        'Dependencies are proactively surfaced and resolved before PI Planning nearly every time',
      ],
    },
    {
      id: 'p3q7',
      dimension: 'flow-execution',
      text: 'How would you characterize current average lead time from idea or feature request to production release?',
      options: [
        'Measured in quarters or longer (or not measured)',
        'Measured in months (two to three-plus months)',
        'Measured in several weeks',
        'Measured in one to two weeks',
        'Measured in days',
      ],
    },
    {
      id: 'p3q8',
      dimension: 'flow-execution',
      text: 'Do teams and ARTs use flow data to make real-time adjustments to plans, or is the data reviewed only retrospectively, if at all?',
      options: [
        "Flow data isn't used to adjust plans; decisions are made ad hoc",
        'Data is reviewed only retrospectively, if at all',
        'Data is reviewed at PI boundaries to adjust plans',
        'Data is reviewed regularly (e.g., each iteration) and used to adjust',
        'Data drives continuous, real-time adjustments to plans and priorities',
      ],
    },

    // ── PILLAR 4: Technical Engineering & Architecture ───────────────────────
    {
      id: 'p4q1',
      dimension: 'technical-engineering',
      text: 'What percentage of deployments are fully automated end-to-end, without a manual approval gate?',
      options: [
        '0% — deployments are entirely manual',
        'Some automation exists but manual gates dominate (under 25% automated)',
        '25–60% automated',
        '60–90% automated',
        'Over 90% automated, with minimal manual gates',
      ],
    },
    {
      id: 'p4q2',
      dimension: 'technical-engineering',
      text: 'Do teams practice Test-Driven Development and/or Behavior-Driven Development as standard practice, not an exception?',
      options: [
        'TDD/BDD is not practiced',
        'TDD/BDD is attempted occasionally by individual engineers',
        'TDD/BDD is standard on at least one team/ART',
        'TDD/BDD is standard practice across most teams',
        'TDD/BDD is enterprise-standard practice, enforced and measured',
      ],
    },
    {
      id: 'p4q3',
      dimension: 'technical-engineering',
      text: 'Is architectural runway work — decoupling, API abstraction, technical debt remediation — an explicitly funded and tracked backlog item?',
      options: [
        'No architectural runway backlog exists',
        'Runway needs are identified but unfunded',
        'Runway work is funded and tracked for some initiatives',
        'Runway work is consistently funded (roughly 40%+) and tracked',
        'Runway investment is a standing, protected portion of every portfolio cycle',
      ],
    },
    {
      id: 'p4q4',
      dimension: 'technical-engineering',
      text: 'What is your current deployment frequency?',
      options: [
        'Quarterly or less frequent',
        'Monthly',
        'Weekly',
        'Daily',
        'On-demand / multiple times per day',
      ],
    },
    {
      id: 'p4q5',
      dimension: 'technical-engineering',
      text: 'Is security scanning (DevSecOps) integrated and automated within the CI/CD pipeline, rather than a separate manual gate?',
      options: [
        'No security scanning is integrated into the pipeline',
        'Manual security review exists as a separate gate',
        'Some automated scanning exists but is inconsistent',
        'Automated scanning is integrated into CI/CD for most pipelines',
        'Automated scanning is fully integrated and blocking across all pipelines',
      ],
    },
    {
      id: 'p4q6',
      dimension: 'technical-engineering',
      text: 'Can technical deployment happen independently of business release, for example through feature toggles or dark launches?',
      options: [
        'Deployment and release are the same event; no decoupling capability',
        'Feature toggles are used occasionally, with limited decoupling',
        'Feature toggles/dark launches are used for select features',
        'Decoupled deployment/release is standard for most teams',
        'Deployment is fully decoupled from release enterprise-wide (toggles, blue/green, canary as default)',
      ],
    },
    {
      id: 'p4q7',
      dimension: 'technical-engineering',
      text: 'What is your current change failure rate and mean time to recovery from a failed deployment?',
      options: [
        "Change failure rate is high and/or MTTR is measured in days, or isn't tracked",
        'Both are tracked but consistently poor',
        'Moderate change failure rate; MTTR measured in hours',
        'Low change failure rate (under ~15%); MTTR under an hour',
        'Very low change failure rate; MTTR measured in minutes, self-healing common',
      ],
    },
    {
      id: 'p4q8',
      dimension: 'technical-engineering',
      text: "Does your architecture (monolith versus decoupled/microservices) currently constrain a team or ART's ability to deploy independently?",
      options: [
        'Monolithic architecture prevents any team from deploying independently',
        'Some decoupling exists but most teams are still blocked by shared dependencies',
        'Partial decoupling allows some teams/ARTs to deploy independently',
        'Most teams/ARTs can deploy independently with minimal coordination',
        'Architecture fully supports independent deployment for all teams/ARTs',
      ],
    },

    // ── PILLAR 5: Leadership, Culture & Talent Capability ────────────────────
    {
      id: 'p5q1',
      dimension: 'leadership-culture',
      text: 'What percentage of tactical or technical decisions currently require executive or middle-management approval?',
      options: [
        'Over 75% require approval',
        '50–75%',
        '25–50%',
        '10–25%',
        'Under 10% — decisions are decentralized to teams',
      ],
    },
    {
      id: 'p5q2',
      dimension: 'leadership-culture',
      text: 'Is there a staffed Lean-Agile Center of Excellence (or equivalent function) actively training RTEs, Scrum Masters, and Product Owners?',
      options: [
        'No LACE or equivalent function exists',
        "An informal group exists but isn't staffed or funded",
        'A LACE is established but limited in reach or training capacity',
        'A LACE is staffed and actively training most role-holders',
        'A LACE is fully staffed, and training is continuous and enterprise-wide',
      ],
    },
    {
      id: 'p5q3',
      dimension: 'leadership-culture',
      text: 'Are individual performance evaluations based on team or velocity metrics, or on broader contribution and behavior?',
      options: [
        'Evaluations are directly tied to velocity/output metrics',
        'Velocity is an informal factor in evaluations',
        'Evaluations mix velocity with some behavioral/team criteria',
        'Evaluations are primarily behavior/contribution based; velocity is rarely used',
        'Evaluations never use team velocity; focus is entirely on individual growth and team contribution',
      ],
    },
    {
      id: 'p5q4',
      dimension: 'leadership-culture',
      text: 'If a key role — RTE, Architect, Product Manager — left tomorrow, could the ART continue delivering without a significant stall?',
      options: [
        'A single key departure would likely halt delivery',
        'Departure would cause significant delay, but delivery would eventually resume',
        'Some redundancy exists for a subset of key roles',
        'Most key roles have backup or succession coverage',
        'Full bench strength — any key departure causes minimal disruption',
      ],
    },
    {
      id: 'p5q5',
      dimension: 'leadership-culture',
      text: 'Are failures treated as blameless learning opportunities, or does the organization default to individual blame?',
      options: [
        'Failures typically result in individual blame or reprimand',
        'Blame is common but occasionally softened by leadership',
        'Blameless retrospectives are attempted, but inconsistently',
        'Blameless postmortems are standard practice for most incidents',
        'A blameless learning culture is fully embedded and reinforced by leadership',
      ],
    },
    {
      id: 'p5q6',
      dimension: 'leadership-culture',
      text: 'Has senior leadership received formal Lean-Agile leadership training, and do they visibly model servant leadership behaviors day to day?',
      options: [
        'Leadership has received no Lean-Agile training',
        "Some leaders have attended training, but behavior hasn't changed",
        'Most leaders are trained; behavior change is inconsistent',
        'Leaders are trained and mostly model servant leadership behaviors',
        'Leadership consistently models and reinforces servant leadership org-wide',
      ],
    },
    {
      id: 'p5q7',
      dimension: 'leadership-culture',
      text: 'How long does it take a new team member to reach full productive contribution, and is that time actively tracked or improved?',
      options: [
        'Time-to-competency is not tracked at all',
        'Anecdotal awareness only, with no formal tracking',
        'Tracked for some roles/teams but not acted on',
        'Tracked across most roles and used to improve onboarding',
        'Tracked, actively improved, and demonstrably decreasing over time',
      ],
    },
    {
      id: 'p5q8',
      dimension: 'leadership-culture',
      text: 'Do frontline teams hold real decision-making authority over technical design and scope, or does that authority sit with management?',
      options: [
        'All technical design/scope decisions are made by management',
        'Teams have input, but management makes the final call',
        'Teams decide on some technical matters; management retains scope authority',
        'Teams hold most technical/design authority; management is involved only on major scope',
        'Teams hold full authority over technical design and scope; management only handles strategic decisions',
      ],
    },
  ],
};

export default safeAgileMaturit;
