import type { DiagnosticConfig } from '../types';

const safeAgileMaturit: DiagnosticConfig = {
  slug: 'safe-agile-maturity',
  title: 'SAFe Agile Maturity Assessment',
  description:
    'Assess your organization\'s SAFe Agile maturity across five pillars — Strategy & Lean Portfolio Governance, ART Execution & Flow, Technical Agility & DevOps, Event Quality & Alignment, and Lean-Agile Culture & Leadership — and receive a prioritized improvement roadmap.',
  scoreDisplay: 'normalized',
  dimensions: [
    { id: 'strategy-lpg',       label: 'Strategy & Lean Portfolio Governance',              shortName: 'Strategy & LPG' },
    { id: 'art-execution',      label: 'Agile Release Train Execution & Flow Acceleration', shortName: 'ART Execution' },
    { id: 'technical-agility',  label: 'Technical Agility & DevOps Engineering',            shortName: 'Technical Agility' },
    { id: 'event-quality',      label: 'Event Quality & Organizational Alignment',          shortName: 'Event Quality' },
    { id: 'culture-leadership', label: 'Lean-Agile Culture & Leadership Mindset',           shortName: 'Culture & Leadership' },
  ],
  questions: [
    // ── PILLAR 1: Strategy & Lean Portfolio Governance ──────────────────────
    {
      id: 'p1q1',
      dimension: 'strategy-lpg',
      text: 'How is software/product investment funded?',
      options: [
        'Annual, fixed-scope, project-based cost-center budgets with phase-gated approvals',
        'Strategic Themes communicated to engineering management; funding still tied to annual project cycles',
        'Continuous Value Stream funding has replaced project-based budgets; Lean Portfolio Management (LPM) operationalized',
        'Portfolio funding adjusts dynamically via participatory budgeting cycles tied to real-time flow metrics and OKRs',
        'Continuous, real-time capital reallocation driven by predictive market signals and AI-driven forecasting',
      ],
    },
    {
      id: 'p1q2',
      dimension: 'strategy-lpg',
      text: 'Are Strategic Themes defined and connected to execution?',
      options: [
        'No defined Strategic Themes; priorities are ad hoc and short-term',
        'Initial Strategic Themes exist and are communicated to engineering leadership',
        'Strategic Themes are formally linked to Portfolio Epics and tracked via OKRs',
        'OKR achievement directly informs dynamic funding and prioritization decisions',
        'Strategy and execution operate in continuous real-time sync enterprise-wide',
      ],
    },
    {
      id: 'p1q3',
      dimension: 'strategy-lpg',
      text: 'How is feature/epic prioritization performed?',
      options: [
        'No formal prioritization method; decisions driven by individual demands or politics',
        'Basic WSJF scoring introduced for features at the program level',
        'Portfolio Epics formally prioritized via WSJF and tracked on a Portfolio Kanban',
        'WSJF and portfolio prioritization are continuously recalibrated against live flow data',
        'Prioritization is automated/AI-assisted using predictive demand and economic modeling',
      ],
    },
    {
      id: 'p1q4',
      dimension: 'strategy-lpg',
      text: 'Is a Portfolio Kanban used to manage work-in-process at the executive tier?',
      options: [
        'No portfolio-level visualization of work exists',
        'Informal tracking of features in program backlogs only',
        'A formal Portfolio Kanban is established and actively used to limit portfolio WIP',
        'Portfolio Kanban is integrated with automated epic-tracking dashboards',
        'Portfolio flow is managed in real time with enterprise-wide visibility and adaptive limits',
      ],
    },
    {
      id: 'p1q5',
      dimension: 'strategy-lpg',
      text: 'Are Objectives and Key Results (OKRs) used to connect strategy to execution?',
      options: [
        'OKRs are not used; success is measured by output/activity only',
        'OKRs are being introduced informally at team or program level',
        'OKRs are formally used to link strategy to execution and are tracked against Flow Metrics',
        'OKR achievement directly drives dynamic funding and portfolio decisions',
        'OKRs, flow data, and market signals combine in a continuous adaptive planning engine',
      ],
    },
    {
      id: 'p1q6',
      dimension: 'strategy-lpg',
      text: 'How does the organization respond to changing market or business conditions?',
      options: [
        'Rigid annual plans with no mechanism to reallocate funding mid-cycle',
        'Some ability to reprioritize features within a program, but funding is fixed',
        'Participatory budgeting allows periodic (quarterly) reallocation across value streams',
        'Funding shifts dynamically based on real-time flow metrics, OKRs, and market feedback',
        'Capital is continuously reallocated in real time based on predictive market signals',
      ],
    },
    {
      id: 'p1q7',
      dimension: 'strategy-lpg',
      text: 'How aligned are executive leadership, business owners, and system architects on strategy?',
      options: [
        'Little to no shared understanding; software treated as a reactive cost center',
        'Strategic Themes are communicated but decision authority stays centralized',
        'Active alignment exists among leadership, business owners, and architects through LPM',
        'Cross-functional leadership alignment drives dynamic, data-informed funding decisions',
        'Enterprise strategy and execution operate as one continuously aligned adaptive system',
      ],
    },
    {
      id: 'p1q8',
      dimension: 'strategy-lpg',
      text: 'For regulated / complex solution contexts, are compliance and Solution Intent artifacts integrated into portfolio planning?',
      options: [
        'Compliance and architecture requirements are handled ad hoc, outside portfolio planning',
        'Compliance considerations are noted but not systematically built into portfolio decisions',
        'Solution Intent and compliance/auditability artifacts are formally incorporated into portfolio governance',
        'Compliance and architectural runway needs are proactively modeled into dynamic funding decisions',
        'Compliance, audit, and architecture requirements are embedded in real-time adaptive portfolio governance',
      ],
    },

    // ── PILLAR 2: Agile Release Train Execution & Flow Acceleration ──────────
    {
      id: 'p2q1',
      dimension: 'art-execution',
      text: 'Has the organization established Agile Release Trains (ARTs) with a synchronized cadence?',
      options: [
        'No ARTs exist; delivery relies on isolated teams with uncoordinated schedules',
        'Initial ART(s) launched with a fixed Program Increment (PI) cadence and synchronized iterations',
        'Multiple ARTs synchronize cadence across Solution Trains',
        'ART cadence and flow are optimized in real time across multi-train ecosystems',
        'Frictionless, continuous value flow operates across global value streams',
      ],
    },
    {
      id: 'p2q2',
      dimension: 'art-execution',
      text: 'How are cross-team and cross-train dependencies managed?',
      options: [
        'Dependencies are unmanaged, causing high cross-departmental handoffs and long queues',
        'Dependencies are tracked manually across team boards during planning',
        'Cross-team dependencies are proactively managed and tracked across trains',
        'Handoffs are minimized through cross-functional team restructuring',
        'Automated, real-time queue balancing and dependency management occur across value streams',
      ],
    },
    {
      id: 'p2q3',
      dimension: 'art-execution',
      text: 'Is Work in Process (WIP) visualized and limited?',
      options: [
        'WIP is unmanaged; stagnant development queues accumulate',
        'Basic Program Kanban used to visualize feature movement, with initial WIP monitoring',
        'WIP limits are systematically tracked as part of Flow Metrics management',
        'WIP limits are strictly and automatically enforced across development workflows',
        'Continuous, automated WIP and queue balancing operates enterprise-wide',
      ],
    },
    {
      id: 'p2q4',
      dimension: 'art-execution',
      text: 'Are SAFe Flow Metrics (Velocity, Time, Load, Efficiency, Distribution, Predictability) tracked?',
      options: [
        'No flow metrics are tracked',
        'Flow metrics tracking is not yet established beyond basic velocity',
        'Flow Metrics are systematically tracked across ARTs and visualized on dashboards',
        'Flow Metrics actively drive WIP limits, batch size, and queue-shortening decisions',
        'Flow Metrics feed real-time, automated optimization across the value stream ecosystem',
      ],
    },
    {
      id: 'p2q5',
      dimension: 'art-execution',
      text: 'To what extent are the SAFe Eight Flow Accelerators (WIP limits, smaller batches, shorter queues, fewer handoffs, faster feedback, legacy policy removal, etc.) operationalized?',
      options: [
        'Flow accelerators are not applied; large batches, long queues, and frequent handoffs dominate',
        'Awareness exists but accelerators are applied inconsistently, if at all',
        'Flow accelerators are actively identified and systematically addressed',
        'Flow accelerators are fully operationalized with measurable throughput improvement',
        'Flow optimization is continuous, automated, and driven directly by end-user demand telemetry',
      ],
    },
    {
      id: 'p2q6',
      dimension: 'art-execution',
      text: 'How mature is the organization\'s approach to legacy policy remediation that impedes flow?',
      options: [
        'Legacy policies and approval gates are unexamined and routinely block delivery',
        'Some legacy policies have been identified but remain largely unaddressed',
        'Legacy delivery policies are actively identified and remediated',
        'Legacy policy remediation is a standard, ongoing part of flow optimization',
        'Policy and process constraints are continuously monitored and removed in real time',
      ],
    },
    {
      id: 'p2q7',
      dimension: 'art-execution',
      text: 'What is the typical lead time from idea/feature request to production realization?',
      options: [
        'Lead times are long, unpredictable, and undocumented',
        'Lead times are tracked at a basic level but remain long due to handoffs and queues',
        'Lead times are measured systematically and bottlenecks are identified',
        'Lead times are meaningfully reduced through accelerator adoption and automation',
        'Lead time from idea to realization is measured in days, driven by continuous flow',
      ],
    },
    {
      id: 'p2q8',
      dimension: 'art-execution',
      text: 'How are ART-level roles (RTE, Product Management, System Architecture) collaborating to prevent downstream blockages?',
      options: [
        'Roles operate in silos with little coordination ahead of execution',
        'Basic coordination occurs primarily during PI Planning events',
        'RTEs, Product Management, and Architecture proactively map and mitigate dependencies before execution',
        'Cross-functional collaboration is continuous and tightly integrated into flow management',
        'Cross-role collaboration is real-time and automated across the multi-train ecosystem',
      ],
    },

    // ── PILLAR 3: Technical Agility & DevOps Engineering ────────────────────
    {
      id: 'p3q1',
      dimension: 'technical-agility',
      text: 'How mature are built-in quality practices (TDD, BDD, pair programming, refactoring)?',
      options: [
        'Little to no automated testing; manual regression testing performed late in the cycle',
        'Basic automated unit testing established; architectural runway just beginning',
        'TDD/BDD and automated integration testing are broadly standardized',
        'Built-in quality is embedded across all delivery, supporting continuous deployment',
        'Quality practices are continuously reinforced by AI-driven automated testing and anomaly detection',
      ],
    },
    {
      id: 'p3q2',
      dimension: 'technical-agility',
      text: 'What is the state of Continuous Integration (CI)?',
      options: [
        'Code commits are uncoordinated with no automated build/test verification',
        'Basic CI/CD server automation exists with automated build verification testing',
        'Automated integration testing and staging deployments are standard practice',
        'Continuous integration is fully automated and integrated with deployment pipelines',
        'CI infrastructure is cloud-native, AI-integrated, and self-healing',
      ],
    },
    {
      id: 'p3q3',
      dimension: 'technical-agility',
      text: 'How automated is the deployment pipeline (Continuous Delivery Pipeline / CDP)?',
      options: [
        'Deployments are manual, infrequent, and high-risk',
        'Initial CDP established with basic CI and automated unit testing',
        'Automated integration testing and staging deployments occur routinely',
        'Code is deployed continuously to production behind feature toggles',
        'Deployment infrastructure is fully defined as code with automated, zero-downtime releases',
      ],
    },
    {
      id: 'p3q4',
      dimension: 'technical-agility',
      text: 'Is architecture decoupled to support independent release (feature toggles, microservices, blue/green deployment)?',
      options: [
        'Monolithic legacy architecture with no decoupling mechanisms',
        'Early architectural runway work is underway to enable future decoupling',
        'Some decoupling patterns are in place supporting staged/tested deployments',
        'Feature toggles, blue/green deployment, and dark launching are fully realized',
        'Architecture is cloud-native and self-healing, fully decoupled from release cadence',
      ],
    },
    {
      id: 'p3q5',
      dimension: 'technical-agility',
      text: 'Is security (DevSecOps) integrated into the delivery pipeline?',
      options: [
        'Security review happens late, manually, outside the delivery pipeline',
        'Security checks are informal and not integrated into CI/CD',
        'SecOps is integrated into build pipelines alongside expanding test automation',
        'Automated DevSecOps scanning is standard across the continuous deployment process',
        'Automated DevSecOps and continuous security analysis run in real time enterprise-wide',
      ],
    },
    {
      id: 'p3q6',
      dimension: 'technical-agility',
      text: 'Is "Release on Demand" (decoupling technical deployment from business release) achieved?',
      options: [
        'Deployment and release are the same high-risk event',
        'Deployment and release are still tightly coupled, with limited automation',
        'Deployment and release are beginning to decouple via early feature-flag use',
        'Release on Demand is fully realized; deployment is a routine operational process',
        'Release on Demand operates continuously with instant, automated rollback capability',
      ],
    },
    {
      id: 'p3q7',
      dimension: 'technical-agility',
      text: 'How cloud-native and infrastructure-as-code mature is the technical environment?',
      options: [
        'Infrastructure is manually provisioned and managed',
        'Some automation exists, but infrastructure is largely manually configured',
        'Infrastructure automation is expanding alongside CI/CD maturity',
        'Infrastructure as code is broadly adopted, supporting continuous deployment',
        'Infrastructure is fully defined as code, cloud-native, and self-healing',
      ],
    },
    {
      id: 'p3q8',
      dimension: 'technical-agility',
      text: 'Is AI used to support testing, anomaly detection, or rollback decisions?',
      options: [
        'No AI-assisted tooling is used in engineering or operations',
        'AI use is exploratory or limited to isolated experiments',
        'Some automated testing/analysis tools are in place, though not AI-driven',
        'AI-assisted code analysis or testing is being adopted in select pipelines',
        'AI-driven automated testing, anomaly detection, and self-healing systems are in production',
      ],
    },

    // ── PILLAR 4: Event Quality & Organizational Alignment ──────────────────
    {
      id: 'p4q1',
      dimension: 'event-quality',
      text: 'How well-prepared and effective are PI Planning events?',
      options: [
        'Events lack clear agendas; planning is uncoordinated, causing frequent mid-sprint scope changes',
        'PI Planning is standardized on a fixed quarterly cadence with basic risk/dependency mapping',
        'PI Planning functions as an objective feedback loop with clear preparation and confidence votes',
        'Pre-planning preparation is thorough; complex architectural alignment is resolved before execution',
        'Planning duration and structure adapt dynamically based on flow metrics and delivery stability',
      ],
    },
    {
      id: 'p4q2',
      dimension: 'event-quality',
      text: 'Do System Demos showcase working, integrated software rather than status updates?',
      options: [
        'System Demos do not occur, or are administrative status reporting sessions',
        'System Demos are executed on a fixed cadence but often show partial or non-integrated work',
        'System Demos consistently feature working software in staging environments',
        'System Demos focus on validating complex architectural and value design decisions',
        'Demo cadence and format adapt in real time based on delivery data',
      ],
    },
    {
      id: 'p4q3',
      dimension: 'event-quality',
      text: 'Do Inspect & Adapt (I&A) workshops produce concrete, actionable backlog improvements?',
      options: [
        'I&A workshops do not occur or produce only superficial complaints',
        'I&A workshops occur but rarely translate into backlog action',
        'I&A systematically resolves root causes and yields concrete backlog items',
        'I&A drives cross-train dependency reduction and architectural improvement',
        'I&A operates as a frictionless, continuously adapting alignment mechanism',
      ],
    },
    {
      id: 'p4q4',
      dimension: 'event-quality',
      text: 'Are cross-team and cross-train dependencies resolved before iteration/PI execution begins?',
      options: [
        'No structured process exists to identify dependencies before execution starts',
        'Dependency boards are created during planning, but resolution is inconsistent',
        'Dependencies are systematically resolved through structured multi-team planning',
        'Cross-train dependencies are resolved prior to execution with high team autonomy',
        'Dependency resolution is continuous and adjusts automatically based on flow data',
      ],
    },
    {
      id: 'p4q5',
      dimension: 'event-quality',
      text: 'How effective are ART syncs and team-level ceremonies at driving alignment (vs. status reporting)?',
      options: [
        'Team syncs focus strictly on task status with no cross-team alignment',
        'Synchronized planning sessions establish committed objectives across teams',
        'Retrospectives and syncs actively drive backlog adjustments and dependency reduction',
        'Ceremony friction is minimal; events run with high autonomy and rapid consensus',
        'Ceremonies operate as frictionless, real-time alignment mechanisms',
      ],
    },
    {
      id: 'p4q6',
      dimension: 'event-quality',
      text: 'For distributed/multi-timezone teams, are events structured and tool-supported for effective asynchronous participation?',
      options: [
        'No structured support exists for distributed planning; alignment suffers',
        'Basic tooling is used, but distributed participation is largely improvised',
        'Structured, tool-supported asynchronous preparation is used for multi-timezone planning',
        'Digital planning environments are well established and effective across time zones',
        'Distributed events run seamlessly with real-time, data-driven adaptation',
      ],
    },
    {
      id: 'p4q7',
      dimension: 'event-quality',
      text: 'Is ceremony time weighted toward administrative overhead or genuine feedback loops?',
      options: [
        'Ceremonies are largely administrative status reporting with little value delivered',
        'Ceremonies follow standard structure but still carry meaningful administrative overhead',
        'Ceremonies function as objective feedback loops with clear improvement outcomes',
        'Ceremony overhead is minimized; time is focused on high-value alignment and design',
        'Administrative overhead is eliminated in favor of continuous outcome alignment',
      ],
    },
    {
      id: 'p4q8',
      dimension: 'event-quality',
      text: 'Do events adapt their format/duration based on data (e.g., flow metrics, delivery stability)?',
      options: [
        'Event structure and duration are fixed regardless of team performance or need',
        'Events follow a fixed cadence/format with no adaptation based on data',
        'Some adjustments to event structure are made based on team feedback',
        'Event structure is regularly adjusted based on flow and delivery data',
        'Event duration and format dynamically adjust in real time based on flow metrics',
      ],
    },

    // ── PILLAR 5: Lean-Agile Culture & Leadership Mindset ───────────────────
    {
      id: 'p5q1',
      dimension: 'culture-leadership',
      text: 'What leadership style predominates (command-and-control vs. servant leadership/coaching)?',
      options: [
        'Command-and-control management dominates; rigid commitments are demanded',
        'Leadership has attended SAFe training but still struggles to delegate authority',
        'Leaders actively function as coaches, delegating tactical decisions to teams',
        'Leadership focuses strictly on portfolio economics; teams own technical design',
        'Leadership fosters a resilient, learning-organization culture enterprise-wide',
      ],
    },
    {
      id: 'p5q2',
      dimension: 'culture-leadership',
      text: 'How would you characterize psychological safety on delivery teams?',
      options: [
        'Low psychological safety; failure is penalized and technical debt is hidden',
        'Some awareness of psychological safety, but teams remain cautious about surfacing issues',
        'Decentralized decision-making supports growing transparency about impediments',
        'High psychological safety with widespread delegation of authority',
        'Psychological safety is pervasive, enabling a culture of open experimentation',
      ],
    },
    {
      id: 'p5q3',
      dimension: 'culture-leadership',
      text: 'To what extent is decision-making decentralized to feature teams (SAFe Principle #9)?',
      options: [
        'Executive management retains control over most operational and technical decisions',
        'Management supports ARTs but still retains most decision authority',
        'Decentralized decision-making is implemented for local feature scope',
        'Local Product Owners and engineering leads hold full authority over scope and design',
        'Decision-making authority is fully distributed within an adaptive, self-organizing enterprise',
      ],
    },
    {
      id: 'p5q4',
      dimension: 'culture-leadership',
      text: 'Are velocity or other team metrics used for individual performance evaluation (an anti-pattern)?',
      options: [
        'Velocity and output metrics are used to evaluate individuals, encouraging metric gaming',
        'Some individual performance pressure persists, though less overt',
        'Metrics are used at team level for transparency, not individual evaluation',
        'Leadership actively avoids using flow/velocity metrics for individual evaluation',
        'Metrics are used solely to support organizational learning and continuous improvement',
      ],
    },
    {
      id: 'p5q5',
      dimension: 'culture-leadership',
      text: 'Is failure treated as a learning opportunity (Relentless Improvement)?',
      options: [
        'Failure is penalized, driving teams to hide problems and technical debt',
        'Awareness of Lean-Agile values exists but blame culture persists in practice',
        'Teams self-organize and transparently report delivery impediments',
        'Continuous learning time is built directly into iteration cadences',
        'A continuous learning and improvement culture is deeply ingrained enterprise-wide',
      ],
    },
    {
      id: 'p5q6',
      dimension: 'culture-leadership',
      text: 'How transparent is reporting of delivery status and impediments across team boundaries?',
      options: [
        'Reporting is guarded; impediments are hidden to avoid penalty',
        'Reporting occurs but tends to protect individual/team image',
        'Transparent reporting of impediments is normalized within teams',
        'Transparency extends across team and portfolio boundaries',
        'Transparency is a cultural norm reinforced enterprise-wide',
      ],
    },
    {
      id: 'p5q7',
      dimension: 'culture-leadership',
      text: 'Has the organization invested in executive coaching / organizational change management to shift culture?',
      options: [
        'No investment in executive coaching or change management',
        'Leadership has attended introductory SAFe/Lean-Agile training',
        'Coaching supports leaders in shifting to a servant-leadership model',
        'Executive coaching has produced measurable delegation and behavior change',
        'Coaching and change management are embedded as ongoing organizational capabilities',
      ],
    },
    {
      id: 'p5q8',
      dimension: 'culture-leadership',
      text: 'Do career paths and team structures support cross-functional autonomy and growth?',
      options: [
        'Career paths are rigid and tied to functional silos',
        'Some cross-functional exposure exists but is not formally supported',
        'Cross-functional autonomy is actively encouraged at the team level',
        'Career development paths explicitly support cross-functional growth',
        'Personal growth and organizational agility are fully aligned enterprise-wide',
      ],
    },
  ],
};

export default safeAgileMaturit;
